### ISSUE TITLE
Error in  ghcr.io/floppy/van_dam:latest

### ISSUE THREAD

**Issue by ksuquix** [Floppy/van_dam#808]
07:36:09 rails.1  | /usr/src/app/vendor/bundle/ruby/3.1.0/gems/rack-2.2.4/lib/rack/urlmap.rb:34:in `block in remap': paths need to start with / (ArgumentError)

I pulled the new image to update with the latest changes, it appears to be unhappy now.

related: 
Is it possible to push not just :latest, but also the :0.32.0, etc?    That will make it easier to recover from issues.

**Comment by Floppy** [comment]
I noticed this morning that my release last night hadn't worked, sorry about that! Thanks for the error report, I'll see if I can push out a patch quickly.

Good point on the pushes for other versions; I thought it would be doing that, but I'll investigate if it's not.

**Comment by Floppy** [comment]
Looks to me like the other tags should be available to pull: https://github.com/Floppy/van_dam/pkgs/container/van_dam. `docker pull ghcr.io/floppy/van_dam:0.32.0` worked fine for me - is that different for you?

**Comment by Floppy** [comment]
Should be fixed in v0.33.1; it was an error that only showed up when running the version built by Docker, so it slipped through my net. Sorry about that!

**Comment by ksuquix** [comment]
My bad.   Still getting a bit used to docker (hard to break 26 years of various unix patterns).   Apparently docker inspect only works on images you've already done a docker pull on.
